Django/crm/djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

# from leads.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home_page),
    path('leads/', include("leads.urls", namespace="leads")),
    path('agents/', include("agents.urls", namespace="agents")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Django/crm/leads/urls.py
from django.urls import path

from .views import HomePage, home_page, lead_detail, lead_create, leadCreate, lead_update, leadUpdate, lead_delete

app_name = "leads"

urlpatterns = [
    # path('', home_page, name='home_page'),
    path('', HomePage.as_view(), name='home_page'),
    path('<int:pk>/', lead_detail, name='lead_detail'),
    path('create/', lead_create, name='lead_create'),
    path('<int:pk>/update/', lead_update, name='lead_update'),
    path('lead-create/', leadCreate, name='lead-create'),
    path('<int:pk>/lead-update/', leadUpdate, name='lead-update'),
    path('<int:pk>/delete/', lead_delete, name='lead_delete'),
    
]

Django/crm/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>djCRM</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        {% include 'styles.html' %}
        {% block content %}
        {% endblock content %}
        {% include 'scripts.html' %}
    </body>
</html>

Django/crm/templates/lead_list.html
{% extends 'base.html' %}

{% block content %}
    {% comment %} <a href="/leads/lead-create/"> Create Lead </a> {% endcomment %}
    <a href="{% url 'leads:lead-create' %}"> Create Lead </a>
    <hr/>
    <h1> Lead List </h1>
    {% comment %} {{ name }} {{ age }} {% endcomment %}

    {% for lead in leads %}
        <div class="lead">
            {% comment %} <a href="/leads/{{lead.pk}}"> {{ lead.first_name }} {{ lead.last_name }}</a>  {{ lead.age }} {% endcomment %}
            <a href="{% url 'leads:lead_detail' lead.pk %}"> {{ lead.first_name }} {{ lead.last_name }}</a>  {{ lead.age }}
        </div>
    {% endfor %}
{% endblock content %}

Django/crm/templates/scripts.html
{% comment %} <script>
    console.log("Hello!")
</script> {% endcomment %}


{% load static %}
<script src='{% static 'js/main.js' %}'></script>

Django/crm/templates/styles.html
<style>
  .lead {
    width: 25%;
    padding-left: 10px;
    padding-right: 10px;
    margin-bottom: 10px;
    font-color: black;
    background-color: skyblue;
    border: 10px solid skyblue;
  }
  body {
    background-color: powderblue;
  }
  h1 {
    font-family: courier;
  }
  a {
    color: white;
    font-family: verdana;
  }
  p{
    font-family: monospace;
  }
</style>