Django/crm/agents/urls.py
from django.urls import path
from .views import (AgentListView,
    AgentCreateView, AgentDetailView,
    AgentUpdateView, AgentDeleteView
)

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),

]

Django/crm/djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

# from leads.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home_page),
    path('leads/', include("leads.urls", namespace="leads")),
    path('agents/', include("agents.urls", namespace="agents")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Django/crm/agents/models.py
from django.db import models

# Create your models here.

Django/crm/agents/forms.py
from django import forms
from leads.models import Agent


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields = (
            'user',
        )

Django/crm/agents/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from django.shortcuts import reverse
from .forms import AgentModelForm


class AgentListView(LoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        return Agent.objects.all()
    

class AgentCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def form_valid(self, form):
        agent = form.save(commit=False)
        agent.organisation = self.request.user.userprofile
        agent.save()
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = 'agent'
    
    def get_queryset(self):
        return Agent.objects.all()
    

class AgentUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm

    def get_queryset(self):
        return Agent.objects.all()

    def get_success_url(self):
        return reverse("agents:agent-list")


class AgentDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/agent_delete.html'
    context_object_name = 'agent'

    def get_queryset(self):
        return Agent.objects.all()
    
    def get_success_url(self):
        return reverse("agents:agent-list")
    

Django/crm/agents/templates/agents/agent_create.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'agents:agent-list' %}"> Go Back </a>
    <hr/>
    <h1> Create a new Agent </h1>

    <form method='post' action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'> Submit </button>
    </form>
{% endblock content %}

Django/crm/agents/templates/agents/agent_delete.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'agents:agent-detail' agent.pk %}"> Go Back </a>
    <hr/>
    <h1> Are you sure you want to delete {{ agent.user.username }}? </h1>
    <form method='post' action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'> Submit </button>
    </form>
{% endblock content %}

Django/crm/agents/templates/agents/agent_detail.html
{% extends 'base.html' %}

{% block content %}
    <a href="/agents/"> Go Back </a>
    <hr/>
    <h1> Details of {{ agent.user.username }} </h1>
    <p> The agent belongs to {{ agent.organisation }} organisation.</p>
    <hr/>
    <a href="/agents/{{ agent.id }}/update"> Update Agent </a>
    <hr/>
    <a href="/agents/{{ agent.id }}/delete"> Delete Agent </a>
    <hr/>
{% endblock content %}

Django/crm/agents/templates/agents/agent_list.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'agents:agent-create' %}"> Create Agent </a>
    <hr/>
    <h1> Agent List </h1>

    {% for agent in object_list %}
        <div class="agent">
            <a href="{% url 'agents:agent-detail' agent.pk %}"> {{ agent.user.username }}</a>
        </div>
    {% endfor %}
{% endblock content %}

{% comment "object_list" %}
object_list is the default context name for the queryset
{% endcomment %}


{% comment %} {% extends 'base.html' %}
{% block content %}

<h1> Here are our agents </h1>

{% for agent in object_list %}
    {{ agent.user.username }}
{% endfor %}

{% endblock content %} {% endcomment %}

Django/crm/agents/templates/agents/agent_update.html
{% extends 'base.html' %}

{% block content %}
    <a href="/agents"> Go Back </a>
    <hr/>
    <h1> Update Agent: {{ agent.user.username }} </h1>
    <form method='post' action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'> Submit </button>
    </form>
{% endblock content %}